# บล็อก

การ Blocking หรือการจัดบล็อก คือหัวใจสำคัญของการออกแบบการทดลองเพื่อควบคุมความแปรปรวนจากปัจจัยภายนอก โดยเฉพาะความไม่สม่ำเสมอของดิน (Soil Heterogeneity) เพื่อให้การเปรียบเทียบกรรมวิธีมีความแม่นยำสูงสุด

## วัตถุประสงค์และผลของการจัดบล็อก
**เพื่อแยกความแปรปรวน** : การจัดบล็อกช่วยให้เราสามารถแยกความแตกต่างระหว่างบล็อกออกจาก ค่าความคลาดเคลื่อนของการทดลอง (Experimental Error) ได้ ส่งผลให้ค่า Error ลดลงและเพิ่มความแม่นยำ (Precision) ให้กับงานวิจัย

**หลักการสำคัญ** : การจัดบล็อกที่ดีต้องทำให้ หน่วยทดลองภายในบล็อกเดียวกันมีความสม่ำเสมอ (Homogeneous) มากที่สุด แต่ให้ มีความแตกต่างระหว่างบล็อกมากที่สุด

## วิธีการใช้การจัด blocking

-   **เมื่อทราบรูปแบบความอุดมสมบูรณ์ของดิน:** ให้วางแนวบล็อกเพื่อให้ความแตกต่างของดิน "ระหว่างบล็อก" มีค่าสูงสุด และความแตกต่าง "ภายในบล็อก" มีค่าน้อยที่สุด ตัวอย่างเช่น หากแปลงนามีแนวความอุดมสมบูรณ์ต่างกันในทิศทางเดียวตามความยาวของพื้นที่ การจัดกลุ่มควรทำตามแนวขวางของพื้นที่ หรือกล่าวคือ ตัดขวางหรือตั้งฉากกับแนวความแตกต่างนั้น

-   **เมื่อไม่ทราบรูปแบบความอุดมสมบูรณ์ของดิน:** หลีกเลี่ยงการใช้บล็อกที่มีลักษณะยาวและแคบ แต่ควรใช้บล็อกที่มีความกระชับ (Compact) หรือมีรูปทรงใกล้เคียงสี่เหลี่ยมจัตุรัสมากที่สุดเท่าที่จะเป็นไปได้ เนื่องจากแปลงที่อยู่ใกล้กันย่อมมีโอกาสที่จะมีลักษณะเหมือนกันมากกว่าแปลงที่อยู่ห่างกัน

**ขนาดบล็อก**: บล็อกต้องมีพื้นที่เพียงพอที่จะวางแปลงย่อย (Plots) ของทุกกรรมวิธีในชุดนั้นๆ ได้ครบถ้วน หากมีพื้นที่เหลือไม่ควรนำแปลงย่อยของบล็อกอื่นมาแทรก

-   **การจัดการแบบ "รายบล็อก" (Per-block basis)** : เพื่อควบคุมความแปรปรวนที่อาจเกิดขึ้นในกระบวนการจัดการและการปฏิบัติงาน รวมถึงการเก็บข้อมูล ทุกขั้นตอนควรดำเนินการตามรายบล็อก กล่าวคือ เมื่อใดก็ตามที่มีแหล่งความแปรปรวนเกิดขึ้น ให้พยายามแยกความแปรปรวนส่วนใหญ่นั้นออกด้วยการจัดกลุ่ม

    ยกตัวอย่างเช่น หากการดำเนินงานบางอย่าง (เช่น การใส่ทรีตเมนต์ หรือการวัดข้อมูล) ไม่สามารถทำให้เสร็จสิ้นทั้งการทดลองได้ภายในวันเดียว อย่างน้อยที่สุดก็ควรทำงานของทุกแปลงในหนึ่งบล็อกให้เสร็จในวันนั้น เพื่อให้ความแตกต่างของปัจจัยด้านวันเวลาถูกควบคุมโดย "บล็อก"

    เทคนิคเดียวกันนี้สามารถใช้เพื่อจัดการความแปรปรวนระหว่างผู้ปฏิบัติงานได้ เมื่อใดที่งานนั้นได้รับผลกระทบจากทักษะของผู้ปฏิบัติงาน (เช่น การใส่ปุ๋ย การพ่นสารเคมี หรือการวัดความสูงต้น) ควรแบ่งให้ผู้ปฏิบัติงานแต่ละคนรับผิดชอบบล็อกที่แตกต่างกันไป
